services:
  - type: static
    name: portfolio-kenza
    env: static
    buildCommand: npm install && npm run build
    publishDir: dist
    headers:
      - path: /*
        name: Cache-Control
        value: max-age=31536000
